CREATE TABLE IF NOT EXISTS drafts(id TEXT PRIMARY KEY,title TEXT NOT NULL,norm TEXT NOT NULL UNIQUE,domain TEXT NOT NULL,summary TEXT NOT NULL DEFAULT '',author TEXT NOT NULL DEFAULT '',source TEXT NOT NULL,created_at INTEGER NOT NULL,hidden INTEGER NOT NULL DEFAULT 0);
CREATE INDEX IF NOT EXISTS drafts_visible ON drafts(hidden,created_at);
