import {Hono} from 'hono';
import {getCookie,setCookie} from 'hono/cookie';
import {bodyLimit} from 'hono/body-limit';
import {secureHeaders} from 'hono/secure-headers';
import {serveStatic} from 'hono/cloudflare-workers';
import {z} from 'zod';
import page from './page.html?raw';
import original from './original.json';
const proposal=z.object({id:z.string().regex(/^custom-[a-zA-Z0-9-]{1,70}$/),title:z.string().trim().min(1).max(240),domain:z.string().trim().min(1).max(100),desc:z.string().trim().min(1).max(4000),note:z.string().max(2000)}).strict();
const schema=z.object({version:z.literal(1),custom:z.array(proposal).max(100),shortlist:z.array(z.string().max(80)).max(4),reviews:z.record(z.string().max(80),z.object({scores:z.array(z.number().int().min(1).max(5).nullable()).length(4),notes:z.string().max(6000)}).strict()),theme:z.enum(['light','dark'])}).strict().superRefine((s,c)=>{const all=[...original,...s.custom],ids=all.map(p=>p.id);if(new Set(ids).size!==ids.length||new Set(all.map(p=>p.title.toLowerCase())).size!==all.length)c.addIssue({code:'custom',message:'Duplicate proposal title or ID.'});if(new Set(s.shortlist).size!==s.shortlist.length||s.shortlist.some(id=>!ids.includes(id))||Object.keys(s.reviews).some(id=>!ids.includes(id)))c.addIssue({code:'custom',message:'Invalid proposal reference.'})});
const app=new Hono();
app.use('*',secureHeaders({contentSecurityPolicy:{defaultSrc:["'self'"],scriptSrc:["'self'"],styleSrc:["'self'"],connectSrc:["'self'"],imgSrc:["'self'",'data:'],objectSrc:["'none'"],baseUri:["'none'"],frameAncestors:["'none'"],formAction:["'self'"]},referrerPolicy:'no-referrer'}));
app.use('/static/*',serveStatic({root:'./public'}));
app.use('/api/*',async(c,next)=>{c.header('Cache-Control','no-store');if(c.req.method!=='GET'&&(c.req.header('Origin')!==new URL(c.req.url).origin||c.req.header('X-Workspace-Request')!=='1'))return c.json({error:'Request must come from this workspace.'},403);await next()});
app.use('/api/*',bodyLimit({maxSize:262144,onError:c=>c.json({error:'Workspace exceeds 256 KB.'},413)}));
const hash=async t=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(t))),v=>v.toString(16).padStart(2,'0')).join('');
app.get('/api/workspace',async c=>{let token=getCookie(c,'capstone_workspace');if(!token||!/^[a-f0-9]{64}$/.test(token)){token=Array.from(crypto.getRandomValues(new Uint8Array(32)),v=>v.toString(16).padStart(2,'0')).join('');setCookie(c,'capstone_workspace',token,{httpOnly:true,sameSite:'Strict',secure:new URL(c.req.url).protocol==='https:',maxAge:31536000,path:'/'})}const id=await hash(token);await c.env.DB.prepare('INSERT OR IGNORE INTO workspaces(id,data) VALUES(?,?)').bind(id,JSON.stringify({version:1,custom:[],shortlist:[],reviews:{},theme:'light'})).run();const row=await c.env.DB.prepare('SELECT data,revision FROM workspaces WHERE id=?').bind(id).first();return c.json({state:JSON.parse(row.data),revision:row.revision})});
app.put('/api/workspace',async c=>{const token=getCookie(c,'capstone_workspace');if(!token||!/^[a-f0-9]{64}$/.test(token))return c.json({error:'Enable cookies and reload before saving.'},401);let body;try{body=await c.req.json()}catch{return c.json({error:'Invalid JSON.'},400)}const parsed=z.object({revision:z.number().int().nonnegative(),state:schema}).strict().safeParse(body);if(!parsed.success)return c.json({error:parsed.error.issues[0].message},400);const {state,revision}=parsed.data;const r=await c.env.DB.prepare('UPDATE workspaces SET data=?,revision=revision+1 WHERE id=? AND revision=?').bind(JSON.stringify(state),await hash(token),revision).run();if(!r.meta.changes)return c.json({error:'Another tab saved changes. Export your unsaved draft, then reload.'},409);return c.json({revision:revision+1})});
app.get('/api/health',async c=>{await c.env.DB.prepare('SELECT 1 FROM workspaces LIMIT 1').first();return c.json({ok:true,storage:'D1'})});
app.get('/',c=>c.html(page));
app.onError((e,c)=>{console.error(e.message);return c.json({error:'Database unavailable. Keep your form open and retry.'},503)});
export default app;
